### ISSUE TITLE
Slows down copy

### ISSUE THREAD

**Issue by SDAdham** [stringham/copy-with-imports#13] opened 2021-08-30 23:54 UTC
When copying code, it takes a while to be copied which is annoying, specially if you don't have a feedback that it's copied and then you keep switching files and paste an old paste.

disabling the extension, copying code is instant

Since installing the extension, it made copying and pasting more efforts and extra overload.

Please help. If slowing down is a must but at least provide a notification that the copy is ready.
Also, please limit the extension to work only in typescript, javascript, etc.. those that can come with imports but definitely not HTML.

**Comment by stringham** [comment] 2021-08-31 00:02
You can see the code that handles copy [here](https://github.com/stringham/copy-with-imports/blob/521f6f25ca7eaedfe7cbc9e08249fcfa12ae572e/src/extension.ts#L153-L174).

It immediately calls the built-in vscode command to copy, then it just saves off which text was copied so we can handle checking for imports to bring in during paste.

It waits to do almost all of the work until you paste.

I use the extension daily and have never experienced this. Can you give some steps to reproduce?

**Comment by SDAdham** [comment] 2021-08-31 00:55
@stringham I don't know how can I help you reproduce? Press Ctrl+C then Ctrl+V lol

I see it immediately calls the built-in, but it takes time for your extension to kickoff, maybe that's the issue? If I have another extension loading then I press Ctrl+C maybe, VS code waits for the other extension to finish then it runs your extension? I don't know tbh...

**Comment by SDAdham** [comment] 2021-08-31 01:02
I cannot find an event where you can maybe attach event command rather overriding: https://code.visualstudio.com/api/references/activation-events#onCommand

**Comment by SDAdham** [comment] 2021-08-31 02:41
@stringham I really like your extension but on my end, it's really bad sometimes

**Comment by SDAdham** [comment] 2021-11-16 23:51
@stringham can you please add support for notification when the copy is done and paste is done?

**Comment by stringham** [comment] 2021-11-16 23:59
Have you updated to the latest version?

**Comment by SDAdham** [comment] 2021-11-17 13:09
I think so, it says `v0.2.0`
![image](https://user-images.githubusercontent.com/11182824/142206724-f828700a-797b-4a72-a0df-0f97b720ccba.png)
It doesn't say there is a newer version

**Comment by stringham** [comment] 2021-11-17 21:22
I have been unable to reproduce this issue.

Will you create a git repo where you experience the problem, and give steps to reproduce that include what you copy and where you paste?

If I cannot reproduce it then I cannot fix it.

**Comment by SDAdham** [comment] 2021-11-18 12:15
@stringham , there is noway I can really create a repo for this issue, you cannot really reproduce a lag by a code.

**Comment by SDAdham** [comment] 2021-11-18 12:15
I know in the same there is noway you can fix this if you yourself don't experience it. but is it possible taht you can please add a notification for when the copy is processed?

**Comment by stringham** [comment] 2021-11-22 03:01
The extension processes the copy before doing any other work. The only reason copying wouldn't happen immediately is if vscode doesn't invoke the extension.

If vscode doesn't call the extension command it can't show a notification.

If you can help me reproduce the problem you're seeing, I'll take a look.

Since I can't reproduce it right now, I'm going to close this issue.

**Closed by stringham** 2021-11-22 03:01 UTC

**Comment by SDAdham** [comment] 2021-11-23 08:32
Yes @stringham ,

That's correct, it can't show notification straight away, but the moment it starts invokes (after while of wait), I'd at least know that I can start moving forward and paste.

**Comment by SDAdham** [comment] 2021-11-23 08:33
Look, I'm not really asking much, if you don't mind, can you please add notification support, that once the copy is over (with a flag of a setting), it'd invoke the notification?

Again, I cannot help you reproduce a lag. I didn't say it doesn't do the copy. it's just there is a lag.
